* Support vector machine is good for non linear seperable data.
* It converts low dimensional data to high dimensional data.
* It is also good for linear data.
* It converts non linearly seperable data into seperable data.

> Kernels 
1. Linear kernel 
2. Polynomial kernel
3. Sigmoid kernel
4. RBF >> radial basic function >> default 

Hyperparameters >> linear,polynomial,sigmoid,RBF

> margin 
1. Hard margin
2. Soft margin

1. Hard margin 
* It will perfectly segregate all data points.

2. Soft margin
* It will allow some misclassification
* It will have hyperparameter C >> C is term where we define how many misclassifications will be allowed.


* Support vector machine is the most complex algorithm in mathematical calculations.
* Use of Support Vector Machine
1. Used for Supervised Learning algorithms
2. Used for both classification and regression.
3. Mostly used for classification
4. If the data is high dimensional then the algorithm will work good.
5. If the data is non linear then the algorithm will work good.
6. Hyperplane >> Best decision boundary >> 2 features >> straight line
                                        >> 3 features >> 2D plane
                                        >> 4 features >> 3D plane
7. Plane >>> Positive hyperplane
         >>> Negative hyperplane 
* Distance between positive hyperplane and negative hyperplane is defined as Margin.
8. Support Vectors >> Data points which are closest to Hyperplane  >> They help in selecting best hyperplane
* Distance between two support vectors is also defined as Margin.
* Margin should be high as possible .

> Disadvantages
* hyperparameter tuning is required.

* Kernel is used for converting low dimensional data points to high dimensional data points.
* Data can be segregated by adding new features using kernel.
* We have different types of kernel linear,polynomial,sigmoid,Radial basic function(RBF Defualt)

* We have 2 hyperparameters in SVM 
1. C
2. Kernels

In [1]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC,SVR
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [5]:
df["Gender"].value_counts().to_dict()

{'Female': 204, 'Male': 196}

In [6]:
df["Gender"].replace({'Female': 0, 'Male': 1},inplace=True)

In [7]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [13]:
x=df.drop(["User ID","Gender","Purchased"],axis=1)
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
std_scalar = StandardScaler()
array=std_scalar.fit_transform(x)
x=pd.DataFrame(array,columns=x.columns)
x

          Age  EstimatedSalary
0   -1.781797        -1.490046
1   -0.253587        -1.460681
2   -1.113206        -0.785290
3   -1.017692        -0.374182
4   -1.781797         0.183751
..        ...              ...
395  0.797057        -0.844019
396  1.274623        -1.372587
397  1.179110        -1.460681
398 -0.158074        -1.078938
399  1.083596        -0.990844

[400 rows x 2 columns]

In [16]:
x["Gender"] = df["Gender"]

In [17]:
x

          Age  EstimatedSalary  Gender
0   -1.781797        -1.490046       1
1   -0.253587        -1.460681       1
2   -1.113206        -0.785290       0
3   -1.017692        -0.374182       0
4   -1.781797         0.183751       1
..        ...              ...     ...
395  0.797057        -0.844019       0
396  1.274623        -1.372587       1
397  1.179110        -1.460681       0
398 -0.158074        -1.078938       1
399  1.083596        -0.990844       0

[400 rows x 3 columns]

In [18]:
y=df["Purchased"]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

Train test split

In [19]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=22,stratify=y)

Model Training

In [20]:
svm_clf = SVC()
svm_clf.fit(x_train, y_train)

SVC()

Evaluation on Testing Data

In [21]:
y_pred_test = svm_clf.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_test, y_pred_test)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[46  5]
 [ 3 26]]
Clf report:
               precision    recall  f1-score   support

           0       0.94      0.90      0.92        51
           1       0.84      0.90      0.87        29

    accuracy                           0.90        80
   macro avg       0.89      0.90      0.89        80
weighted avg       0.90      0.90      0.90        80

Accuracy:  0.9

Evaluation on TRaining data

In [22]:
y_pred_train = svm_clf.predict(x_train)
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_train, y_pred_train)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[188  18]
 [ 10 104]]
Clf report:
               precision    recall  f1-score   support

           0       0.95      0.91      0.93       206
           1       0.85      0.91      0.88       114

    accuracy                           0.91       320
   macro avg       0.90      0.91      0.91       320
weighted avg       0.91      0.91      0.91       320

Accuracy:  0.9125

Hyperparameter tuning parameter

In [23]:
svm_clf = SVC()
hyperparameters = {"C":np.arange(1,50),
                   "kernel":["linear","poly","rbf","sigmoid"]}
gscv_svm = GridSearchCV(svm_clf,hyperparameters,cv=5)
gscv_svm.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [24]:
gscv_svm.best_estimator_

SVC(C=3)

In [25]:
gscv_svm.best_params_

{'C': 3, 'kernel': 'rbf'}

Evaluation after hyperparameter tuning

In [26]:
svm_clf = gscv_svm.best_estimator_
svm_clf.fit(x_train, y_train)

SVC(C=3)

Evaluation on testing data

In [27]:
y_pred_test = svm_clf.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_test, y_pred_test)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[46  5]
 [ 3 26]]
Clf report:
               precision    recall  f1-score   support

           0       0.94      0.90      0.92        51
           1       0.84      0.90      0.87        29

    accuracy                           0.90        80
   macro avg       0.89      0.90      0.89        80
weighted avg       0.90      0.90      0.90        80

Accuracy:  0.9

Evaluation on Training Data

In [28]:
y_pred_train = svm_clf.predict(x_train)
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_train, y_pred_train)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[189  17]
 [ 10 104]]
Clf report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.93       206
           1       0.86      0.91      0.89       114

    accuracy                           0.92       320
   macro avg       0.90      0.91      0.91       320
weighted avg       0.92      0.92      0.92       320

Accuracy:  0.915625

# SVM >> Support Vector Machine

* Supervised machine learning algorithm
* Used for both classification and regression

1. Linearly seperable data 
2. Non linear data


> Linearly seperable data 
1. Margin
2. Hyperplane 
3. Support vectors
4. Kernels 

1. Margin 
* Distance between positive hyperplane and negative hyperplane is called as margin.
* Distance between two support vectors is called as Margin.

2. Hyperplane 
* Best decision Boundary
* 2 Features >>> Straight line 
* 3 Features >>> 2D Hyperplane
* 4 Features >>> 3D Hyperplane

> Non linearly seperable data

* Kernels 
1. Linear 
2. Polynomial
3. Sigmoid 
4. RBF >> Radial basic function (Default)

* Support vector machine is good for non linear seperable data.
* It converts low dimensional data to high dimensional data.
* It is also good for linear data.
* It converts non linearly seperable data into seperable data.

> Kernels 
1. Linear kernel 
2. Polynomial kernel
3. Sigmoid kernel
4. RBF >> radial basic function >> default 

Hyperparameters >> linear,polynomial,sigmoid,RBF

> margin 
1. Hard margin
2. Soft margin

1. Hard margin 
* It will perfectly segregate all data points.

2. Soft margin
* It will allow some misclassification
* It will have hyperparameter C >> C is term where we define how many misclassifications will be allowed.


* Support vector machine is the most complex algorithm in mathematical calculations.
* Use of Support Vector Machine
1. Used for Supervised Learning algorithms
2. Used for both classification and regression.
3. Mostly used for classification
4. If the data is high dimensional then the algorithm will work good.
5. If the data is non linear then the algorithm will work good.
6. Hyperplane >> Best decision boundary >> 2 features >> straight line
                                        >> 3 features >> 2D plane
                                        >> 4 features >> 3D plane
7. Plane >>> Positive hyperplane
         >>> Negative hyperplane 
* Distance between positive hyperplane and negative hyperplane is defined as Margin.
8. Support Vectors >> Data points which are closest to Hyperplane  >> They help in selecting best hyperplane
* Distance between two support vectors is also defined as Margin.
* Margin should be high as possible .

> Disadvantages
* hyperparameter tuning is required.

* Kernel is used for converting low dimensional data points to high dimensional data points.
* Data can be segregated by adding new features using kernel.
* We have different types of kernel linear,polynomial,sigmoid,Radial basic function(RBF Defualt)

* We have 2 hyperparameters in SVM 
1. C
2. Kernels

# Support vector machine 
* Supervised machine learning algorithm
* Used for both classification and regression 
1. Linearly speperable data 
2. Non linear data 

> Linearly seperable data 
1. Margin 
2. HYperplane 
3. support vector
4. Kernels

1. MArgin 
* Distance between posittive  hyperplane and negative hyperplane is called as Margin
* Distance between two support vectors is called as Margin.

2. Hyperplane
* Best decision boundary 
* 2 features >> Straight line 
* 3 features >> 2D Hyperplane 
* 4 features >> 2D Hyperplane 

> Non linearly seperable data 
* kernels 
1. Linear 
2. Polynomial 
3. Sigmoid 
4. RBF >> Radial basic function 

* Support vector machine is good for non linear seperable data
* It converts low dimensional data to high dimensional data 
* It is also good for linear data 
* It converts non linera seperable data into seperable data 

> Margin 
1. Hard margin 
* It will perfectly segregated all data points

2. Soft margin 
* It will allow some misclassification
* It has hyperparameter C which will allow some misclassification to allow segregation of data points

* Support vector machine is the most complex algorithm in mathematical calculations
> use of support vector machines
* Used for Supervised machine learning algorithms
* Used for boih classification and regression
* Mostly used for classification 
* If the data is high dimensional then it wiil work good 
* If the data is non linear it will work good \
* Hyperplane >> Best decision boundary >> 2 features >> straight line 
                                          3 features >> 2D plane 
                                          4 features >> 3D plane
* Plane >> Positive hyperplane 
        >> Negative hyperplane
* Distance between positive and negative hyperplane is defined as Margin.
* Support vectors >> data points which are closest to hyperpplane >> they help in selecting best hyperplane 
* Distance between two support vectors is also defined as margin.
* Margin should be high as possible

> Disadvantages
* hyperparameter tuning is required
* kernel is used for converting low dimesnional data points to high dimesnional data points
* data can be segregated by adding new features using kernel 
* we have different types of kernel linear,polynomial,sigmoid,radial basic function(RBF Default)

* We have 2 hyperparameter in SVM 
1. C
2. kernels

In [29]:
df=pd.read_csv("Boston.csv")
df

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,502,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,503,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,504,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,505,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,506,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Glucose                   768 non-null    int64
 1   BloodPressure             768 non-null    int64
 2   SkinThickness             768 non-null    int64
 3   Insulin                   768 non-null    int64
 4   BMI                       768 non-null    float64
 5   DiabetesPedigreeFunction  768 non-null    float64
 6   Age                       768 non-null    int64
 7   Outcome                   768 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 48.1 KB

In [32]:
df.describe()

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,121.117188,69.076823,20.536458,79.799479,31.992578,0.471876,33.243490,0.348958
std,31.805091,19.367794,15.952218,115.244002,7.884160,0.331329,11.758182,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,142.000000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [33]:
df=pd.read_csv("diabetes.csv")
df

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,148,50,35,0,33.6,0.627,50,1
1,85,66,29,0,26.6,0.351,31,0
2,183,64,0,0,23.3,0.672,52,1
3,150,66,23,94,28.1,0.167,21,0
4,150,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...
763,101,76,48,180,32.9,0.171,63,0
764,122,70,27,0,36.8,0.340,27,0
765,121,72,23,112,26.2,0.245,30,0
766,126,60,0,0,30.1,0.349,47,1
767,93,70,31,0,30.4,0.315,23,0

In [34]:
import pandas as pd
import numpy as np

from sklearn.svm import SVC,SVR
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
df=pd.read_csv("Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64
 3   EstimatedSalary  400 non-null    int64
 4   Purchased        400 non-null    int64
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

In [38]:
df["Gender"].value_counts().to_dict()

{'Female': 204, 'Male': 196}

In [39]:
df["Gender"].replace({'Female': 0, 'Male': 1},inplace=True)

In [40]:
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510       1   19            19000          0
1    15810944       1   35            20000          0
2    15668575       0   26            43000          0
3    15603246       0   27            57000          0
4    15804002       1   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863       0   46            41000          1
396  15706071       1   51            23000          1
397  15654296       0   50            20000          1
398  15755018       1   36            33000          0
399  15594041       0   49            36000          1

[400 rows x 5 columns]

In [41]:
x=df.drop(["User ID","Gender","Purchased"],axis=1)
x

     Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [42]:
from sklearn.preprocessing import StandardScaler

In [43]:
std_scalar = StandardScaler()
array = std_scalar.fit_transform(x)
x=pd.DataFrame(array,columns=x.columns)
x

          Age  EstimatedSalary
0   -1.781797        -1.490046
1   -0.253587        -1.460681
2   -1.113206        -0.785290
3   -1.017692        -0.374182
4   -1.781797         0.183751
..        ...              ...
395  0.797057        -0.844019
396  1.274623        -1.372587
397  1.179110        -1.460681
398 -0.158074        -1.078938
399  1.083596        -0.990844

[400 rows x 2 columns]

In [44]:
x["Gender"] = df["Gender"]
x

          Age  EstimatedSalary  Gender
0   -1.781797        -1.490046       1
1   -0.253587        -1.460681       1
2   -1.113206        -0.785290       0
3   -1.017692        -0.374182       0
4   -1.781797         0.183751       1
..        ...              ...     ...
395  0.797057        -0.844019       0
396  1.274623        -1.372587       1
397  1.179110        -1.460681       0
398 -0.158074        -1.078938       1
399  1.083596        -0.990844       0

[400 rows x 3 columns]

In [45]:
y=df["Purchased"]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

Train Test Split

In [46]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=12,stratify=y)

Model Training

In [47]:
svm_clf = SVC()
svm_clf.fit(x_train, y_train)

SVC()

Evaluation on Testing Data

In [48]:
y_pred_test = svm_clf.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_test, y_pred_test)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[45  6]
 [ 3 26]]
Clf report:
               precision    recall  f1-score   support

           0       0.94      0.88      0.91        51
           1       0.81      0.90      0.85        29

    accuracy                           0.89        80
   macro avg       0.88      0.89      0.88        80
weighted avg       0.89      0.89      0.89        80

Accuracy:  0.8875

Evaluation on Training Data

In [49]:
y_pred_train = svm_clf.predict(x_train)
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_train, y_pred_train)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[190  16]
 [ 10 104]]
Clf report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94       206
           1       0.87      0.91      0.89       114

    accuracy                           0.92       320
   macro avg       0.91      0.92      0.91       320
weighted avg       0.92      0.92      0.92       320

Accuracy:  0.91875

Hyperparameter tuning

In [50]:
svm_clf = SVC()
hyperparameters = {"C":np.arange(1,50),
                   "kernel":["linear","poly","rbf","sigmoid"]}
gscv_svm = GridSearchCV(svm_clf,hyperparameters,cv=5)
gscv_svm.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [51]:
gscv_svm.best_params_

{'C': 2, 'kernel': 'rbf'}

In [52]:
svm_clf=gscv_svm.best_estimator_
svm_clf.fit(x_train,y_train)

SVC(C=2)

Evalauation after hyperparameter tuning

Evaluation on Testing data

In [53]:
y_pred_test = svm_clf.predict(x_test)
cnf_matrix = confusion_matrix(y_test, y_pred_test)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_test, y_pred_test)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_test, y_pred_test)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[45  6]
 [ 2 27]]
Clf report:
               precision    recall  f1-score   support

           0       0.96      0.88      0.92        51
           1       0.82      0.93      0.87        29

    accuracy                           0.90        80
   macro avg       0.89      0.91      0.89        80
weighted avg       0.91      0.90      0.90        80

Accuracy:  0.9

Evalauation on Training Data

In [54]:
y_pred_train = svm_clf.predict(x_train)
cnf_matrix = confusion_matrix(y_train, y_pred_train)
print("Confusion matrix:\n", cnf_matrix)
clf_report = classification_report(y_train, y_pred_train)
print("Clf report:\n", clf_report)
accuracy = accuracy_score(y_train, y_pred_train)
print("Accuracy: ", accuracy)

Confusion matrix:
 [[190  16]
 [ 10 104]]
Clf report:
               precision    recall  f1-score   support

           0       0.95      0.92      0.94       206
           1       0.87      0.91      0.89       114

    accuracy                           0.92       320
   macro avg       0.91      0.92      0.91       320
weighted avg       0.92      0.92      0.92       320

Accuracy:  0.91875